### ISSUE TITLE
Javascript executes every time

### ISSUE THREAD

**Issue by rept** [peresleguine/pluggable_js#11]
Hi,

First of all thanks for the gem!

I'm having the following issue:

I have one JS file:
pluggable_data.js.coffee

In there I have this code:

    @['company#dashboard'] = (data) ->
      console.log 'company-dashboard'

Now the console.log seems to be executed no matter which page I go to?  I would expect it only to be executed on the company dashboard page.

BTW I'm using turbolinks and have placed the javascript_pluggable_tag in the body part.

Thanks in advance.

**Comment by peresleguine** [comment]
Hello,

Sorry, but I can't confirm this. Double checked everything with turbolinks enabled on rails 4.2.1. Please make sure you have the latest version of the gem, follow the instructions and try again.

I've noticed strange naming of your controller. Usually it would be `companies`. However it shouldn't affect the behaviour.

If you still facing the problem, please post the content of `app/views/layouts/application.html.erb`, `app/assets/javascripts/application.js` and the version of rails used.
