### ISSUE TITLE
How to select more than 1 controller action.

### ISSUE THREAD

**Issue by ssoulless** [peresleguine/pluggable_js#13]
Hi I noticed that I can only select one controller action for every snipet of code, for example

```coffeescript
@['orders#new'] = (data) ->
  somefunctioncall()
@['orders#create'] = (data) ->
  somefunctioncall()
```

Is there a way of specify that I want to run a code snippet for two or more controller actions? like:

```coffeescript
@['orders#new'], @['orders#create'] = (data) ->
  somefunctioncall()
```
This way I do not have to repeat myself... Thanks

**Comment by peresleguine** [comment]
Hello. I suggest to just call function, e.g.:
```coffee
@['orders#new'] = (data) ->
  # main code here

@['orders#create'] = (data) -> @['orders#new'](data)
```
Note that action `create` of any controller is routed to `new` and `update` to `edit` by default: https://github.com/peresleguine/pluggable_js#config
